version: "3.9"

services:
  database:
    image: mysql:8
    restart: unless-stopped
    environment:
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ROOT_HOST: '%'
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_USER: '${DB_USERNAME}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'platform-mysql:/var/lib/mysql'
    networks:
      - platform
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${MYSQL_ROOT_PASSWORD}"]
      retries: 3
      timeout: 5s
    ports:
      - "${MYSQL_EXTERNAL_PORT}:3306"

  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - platform
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s
    ports:
      - "${REDIS_EXTERNAL_PORT}:6379"

  decoder:
    platform: linux/amd64
    image: enjin/platform-decoder:latest
    restart: unless-stopped
    networks:
      - platform
    ports:
      - "${DECODER_EXTERNAL_PORT}:8090"

  app:
    image: enjin/platform:local
    build:
      context: .
    restart: unless-stopped
    environment:
      CONTAINER_ROLE: app
    volumes:
      - '.:/var/www/html'
    networks:
      - platform
    ports:
      - "${APP_EXTERNAL_PORT}:80"
    depends_on:
      - database
      - redis

  ingest:
    image: enjin/platform:local
    restart: unless-stopped
    environment:
      CONTAINER_ROLE: ingest
    volumes:
      - '.:/var/www/html'
    networks:
      - platform
    depends_on:
      - database
      - redis
#      - app

  websocket:
    image: enjin/platform:local
    restart: unless-stopped
    environment:
      CONTAINER_ROLE: websocket
    volumes:
      - '.:/var/www/html'
    networks:
      - platform
    ports:
      - "${SOCKET_EXTERNAL_PORT}:6001"
    depends_on:
      - database
      - redis

  beam:
    image: enjin/platform:local
    restart: unless-stopped
    environment:
      CONTAINER_ROLE: beam
    volumes:
      - '.:/var/www/html'
    networks:
      - platform
    depends_on:
      - database
      - redis

  daemon:
    platform: linux/amd64
    image: enjin/wallet-daemon:latest
    restart: unless-stopped
    env_file:
      - ./daemon/.env
    volumes:
      - ./daemon/config.json:/opt/app/config.json
      - ./daemon/store:/opt/app/storage
    networks:
      - platform
    depends_on:
      - app

networks:
  platform:
    driver: bridge

volumes:
  platform-mysql:
