version: "3.9"

services:
  database:
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD
    volumes:
      - platform-mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${MYSQL_ROOT_PASSWORD}"]
      retries: 3
      timeout: 5s
    ports:
      - "${MYSQL_EXTERNAL_PORT}:3306"

  redis:
    image: redis:alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s
    ports:
      - "${REDIS_EXTERNAL_PORT}:6379"

  decoder:
    image: enjin/decoder:latest
    build:
      context: ./platform-decoder
    restart: unless-stopped
    ports:
      - "${DECODER_EXTERNAL_PORT}:8090"

  app:
    image: enjin/platform:latest
    build:
      context: .
      dockerfile: configs/core/Dockerfile
    restart: unless-stopped
    environment:
      CONTAINER_ROLE: app
    volumes:
      - ./logs:/var/www/html/storage/logs
    depends_on:
      - database
      - redis
    ports:
      - "${APP_EXTERNAL_PORT}:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  websocket:
    image: enjin/platform:latest
    build:
      context: .
      dockerfile: configs/core/Dockerfile
    restart: unless-stopped
    environment:
      CONTAINER_ROLE: websocket
    volumes:
      - ./logs:/var/www/html/storage/logs
    depends_on:
      - database
      - redis
    ports:
      - "${SOCKET_EXTERNAL_PORT}:6001"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ingest:
    image: enjin/platform:latest
    build:
      context: .
      dockerfile: configs/core/Dockerfile
    restart: unless-stopped
    environment:
      CONTAINER_ROLE: ingest
    volumes:
      - ./logs:/var/www/html/storage/logs
    depends_on:
      - database
      - redis
      - app
      - websocket
    extra_hosts:
      - "host.docker.internal:host-gateway"

  beam:
    image: enjin/platform:latest
    build:
      context: .
      dockerfile: configs/core/Dockerfile
    restart: unless-stopped
    environment:
      CONTAINER_ROLE: beam
    volumes:
      - ./logs:/var/www/html/storage/logs
    depends_on:
      - database
      - redis
      - app
      - websocket
      - ingest
    extra_hosts:
      - "host.docker.internal:host-gateway"

  daemon:
    image: enjin/daemon:latest
    build:
      context: .
      dockerfile: configs/daemon/Dockerfile
    restart: unless-stopped
    volumes:
      - ./configs/daemon/store:/opt/app/storage
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  platform-mysql:
