version: "3.9"

services:
  database:
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD
    volumes:
      - platform-mysql:/var/lib/mysql
    networks:
      - platform
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${MYSQL_ROOT_PASSWORD}"]
      retries: 3
      timeout: 5s
    ports:
      - "${MYSQL_EXTERNAL_PORT}:3306"

  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - platform
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s
    ports:
      - "${REDIS_EXTERNAL_PORT}:6379"

  decoder:
    platform: linux/amd64
    image: enjin/platform-decoder:latest
    restart: unless-stopped
    networks:
      - platform
    ports:
      - "${DECODER_EXTERNAL_PORT}:8090"

  app:
    image: enjin/platform:latest
    build:
      context: .
    restart: unless-stopped
    environment:
      CONTAINER_ROLE: app
      WWWUSER: '${WWWUSER}'
      WWWGROUP: '${WWWGROUP}'
    volumes:
      - '.:/var/www/html'
    networks:
      - platform
    ports:
      - "${APP_EXTERNAL_PORT}:80"
    depends_on:
      - database
      - redis

networks:
  platform:
    driver: bridge

volumes:
  platform-mysql:
