name: Publish docker image to DockerHub

on:
  workflow_dispatch:
    
  release:
    types: [created]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_API_USERNAME }}
          password: ${{ secrets.DOCKERHUB_API_TOKEN  }}
      - name: Build and push
        uses: docker/build-push-action@v5
        env:
          DOCKER_REPOSITORY: platform
          IMAGE_TAG: ${{ github.ref_name }}
        with:
          context: .
          file: configs/core/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: enjin/$DOCKER_REPOSITORY:$IMAGE_TAG 